CREATE TABLE "writings" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(256) NOT NULL,
	"title" varchar(256) NOT NULL,
	"description" text NOT NULL,
	"href" varchar(256) NOT NULL,
	"date" varchar(256) NOT NULL,
	"category" varchar(50) NOT NULL,
	"category_label" varchar(50) NOT NULL,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"reading_time" varchar(50) NOT NULL,
	"views" integer DEFAULT 0 NOT NULL,
	"likes" integer DEFAULT 0 NOT NULL,
	"modified_time" varchar(50) NOT NULL,
	"content_path" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "writings_slug_unique" UNIQUE("slug"),
	CONSTRAINT "writings_href_unique" UNIQUE("href")
);
--> statement-breakpoint
CREATE TABLE "notes" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(255) NOT NULL,
	"title" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"href" varchar(255) NOT NULL,
	"date" varchar(50) NOT NULL,
	"column" varchar(50) NOT NULL,
	"column_label" varchar(50) NOT NULL,
	"mood" varchar(50),
	"location" varchar(100),
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"published_at" varchar(50) NOT NULL,
	"views" integer DEFAULT 0 NOT NULL,
	"likes" integer DEFAULT 0 NOT NULL,
	"reading_time" varchar(50) NOT NULL,
	"insight" text NOT NULL,
	"content_path" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "notes_slug_unique" UNIQUE("slug"),
	CONSTRAINT "notes_href_unique" UNIQUE("href")
);
