CREATE TABLE "site_settings" (
	"id" integer PRIMARY KEY DEFAULT 1 NOT NULL,
	"site_name" varchar(120) NOT NULL,
	"site_description" text NOT NULL,
	"site_url" text NOT NULL,
	"rss_url" text NOT NULL,
	"seo_title_template" varchar(160) NOT NULL,
	"seo_keywords" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"seo_description" text NOT NULL,
	"author_name" varchar(80) NOT NULL,
	"avatar_url" text NOT NULL,
	"signature_url" text NOT NULL,
	"contact_email" varchar(160) NOT NULL,
	"github_url" text NOT NULL,
	"netease_music_url" text NOT NULL,
	"douyin_url" text NOT NULL,
	"wechat_qr_url" text NOT NULL,
	"footer_description" text NOT NULL,
	"footer_status_text" varchar(80) NOT NULL,
	"home_hero_prefix" varchar(80) NOT NULL,
	"home_hero_suffix" varchar(120) NOT NULL,
	"home_share_text" varchar(80) NOT NULL,
	"home_location_text" varchar(120) NOT NULL,
	"home_rotating_texts" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"learning_started_at" varchar(40) NOT NULL,
	"motto_code_text" varchar(120) NOT NULL,
	"motto_cn_prefix" varchar(80) NOT NULL,
	"motto_cn_highlight_a" varchar(80) NOT NULL,
	"motto_cn_middle" varchar(80) NOT NULL,
	"motto_cn_highlight_b" varchar(80) NOT NULL,
	"motto_cn_suffix" varchar(80) NOT NULL,
	"motto_en_text" text NOT NULL,
	"friend_page_title" varchar(80) NOT NULL,
	"friend_page_description" text NOT NULL,
	"friend_apply_enabled" boolean DEFAULT true NOT NULL,
	"friend_apply_intro" text NOT NULL,
	"friend_apply_notes" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"friend_own_name" varchar(120) NOT NULL,
	"friend_own_url" text NOT NULL,
	"friend_own_avatar_url" text NOT NULL,
	"friend_own_description" text NOT NULL,
	"friend_apply_success_message" text NOT NULL,
	"admin_page_size" integer DEFAULT 5 NOT NULL,
	"admin_default_entry" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
INSERT INTO "site_settings" (
	"id",
	"site_name",
	"site_description",
	"site_url",
	"rss_url",
	"seo_title_template",
	"seo_keywords",
	"seo_description",
	"author_name",
	"avatar_url",
	"signature_url",
	"contact_email",
	"github_url",
	"netease_music_url",
	"douyin_url",
	"wechat_qr_url",
	"footer_description",
	"footer_status_text",
	"home_hero_prefix",
	"home_hero_suffix",
	"home_share_text",
	"home_location_text",
	"home_rotating_texts",
	"learning_started_at",
	"motto_code_text",
	"motto_cn_prefix",
	"motto_cn_highlight_a",
	"motto_cn_middle",
	"motto_cn_highlight_b",
	"motto_cn_suffix",
	"motto_en_text",
	"friend_page_title",
	"friend_page_description",
	"friend_apply_enabled",
	"friend_apply_intro",
	"friend_apply_notes",
	"friend_own_name",
	"friend_own_url",
	"friend_own_avatar_url",
	"friend_own_description",
	"friend_apply_success_message",
	"admin_page_size",
	"admin_default_entry"
) VALUES (
	1,
	$$Nexora's Space$$,
	$$一个爱捣鼓的前端$$,
	$$https://nexora.space$$,
	$$/rss.xml$$,
	$$%s | Nexora's Space$$,
	'[
		"Next.js",
		"React",
		"Frontend",
		"Blog"
	]'::jsonb,
	$$Nexora's Space 是一个记录前端、生活、思考和长期成长的个人博客。$$,
	$$Nexora$$,
	$$/images/avatar/avatar.jpg$$,
	$$/images/signature/signature.svg$$,
	$$codernexora@foxmail.com$$,
	$$https://github.com/Nexora-ydk$$,
	$$https://music.163.com/#/user/home?id=1598827836$$,
	$$https://www.douyin.com/user/self?from_tab_name=main$$,
	$$/images/wechat-qr.jpg$$,
	$$一个爱捣鼓的前端，记录代码、生活和一些阶段性的想法。$$,
	$$持续折腾中$$,
	$$我是$$,
	$$，一个爱捣鼓的码农$$,
	$$在这里分享$$,
	$$广东 • UTC/GMT +8$$,
	'[
		"记录生活的照片",
		"随性记录的手记",
		"私藏已久的好物",
		"奇妙的代码世界",
		"鲜活的生活切片"
	]'::jsonb,
	$$2026-01-20T00:00:00+08:00$$,
	$$console.log("Hello World")$$,
	$$今天的$$,
	$$“世界你好”$$,
	$$，就是明天的$$,
	$$“改变世界”$$,
	$$。$$,
	$$Today's “Hello World” is tomorrow's change the world.$$,
	$$友链$$,
	$$互联网上走散又相遇的朋友。$$,
	true,
	$$提交后会进入待审核状态，审核通过后公开展示。$$,
	'[
		"请先在你的友链中添加本站",
		"确保你的网站可以正常访问",
		"博客内容不违反国家法律法规"
	]'::jsonb,
	$$nexora$$,
	$$https://nexora.blog/$$,
	$$https://nexora.blog/images/avatar/avatar.jpg$$,
	$$不努力就只能旁听别人的好消息$$,
	$$申请已提交，审核通过后会展示在友链页。$$,
	5,
	$$/admin/writings$$
)
ON CONFLICT ("id") DO NOTHING;
