import { boolean, integer, jsonb, pgTable, text, timestamp, varchar } from "drizzle-orm/pg-core";

export const siteSettings = pgTable("site_settings", {
  id: integer("id").primaryKey().default(1),
  siteName: varchar("site_name", { length: 120 }).notNull(),
  siteDescription: text("site_description").notNull(),
  siteUrl: text("site_url").notNull(),
  rssUrl: text("rss_url").notNull(),
  seoTitleTemplate: varchar("seo_title_template", { length: 160 }).notNull(),
  seoKeywords: jsonb("seo_keywords").$type<string[]>().notNull().default([]),
  seoDescription: text("seo_description").notNull(),
  authorName: varchar("author_name", { length: 80 }).notNull(),
  avatarUrl: text("avatar_url").notNull(),
  signatureUrl: text("signature_url").notNull(),
  contactEmail: varchar("contact_email", { length: 160 }).notNull(),
  githubUrl: text("github_url").notNull(),
  neteaseMusicUrl: text("netease_music_url").notNull(),
  douyinUrl: text("douyin_url").notNull(),
  wechatQrUrl: text("wechat_qr_url").notNull(),
  footerDescription: text("footer_description").notNull(),
  footerStatusText: varchar("footer_status_text", { length: 80 }).notNull(),
  homeHeroPrefix: varchar("home_hero_prefix", { length: 80 }).notNull(),
  homeHeroSuffix: varchar("home_hero_suffix", { length: 120 }).notNull(),
  homeShareText: varchar("home_share_text", { length: 80 }).notNull(),
  homeLocationText: varchar("home_location_text", { length: 120 }).notNull(),
  homeRotatingTexts: jsonb("home_rotating_texts").$type<string[]>().notNull().default([]),
  learningStartedAt: varchar("learning_started_at", { length: 40 }).notNull(),
  mottoCodeText: varchar("motto_code_text", { length: 120 }).notNull(),
  mottoCnPrefix: varchar("motto_cn_prefix", { length: 80 }).notNull(),
  mottoCnHighlightA: varchar("motto_cn_highlight_a", { length: 80 }).notNull(),
  mottoCnMiddle: varchar("motto_cn_middle", { length: 80 }).notNull(),
  mottoCnHighlightB: varchar("motto_cn_highlight_b", { length: 80 }).notNull(),
  mottoCnSuffix: varchar("motto_cn_suffix", { length: 80 }).notNull(),
  mottoEnText: text("motto_en_text").notNull(),
  friendPageTitle: varchar("friend_page_title", { length: 80 }).notNull(),
  friendPageDescription: text("friend_page_description").notNull(),
  friendApplyEnabled: boolean("friend_apply_enabled").notNull().default(true),
  friendApplyIntro: text("friend_apply_intro").notNull(),
  friendApplyNotes: jsonb("friend_apply_notes").$type<string[]>().notNull().default([]),
  friendOwnName: varchar("friend_own_name", { length: 120 }).notNull(),
  friendOwnUrl: text("friend_own_url").notNull(),
  friendOwnAvatarUrl: text("friend_own_avatar_url").notNull(),
  friendOwnDescription: text("friend_own_description").notNull(),
  friendApplySuccessMessage: text("friend_apply_success_message").notNull(),
  adminPageSize: integer("admin_page_size").notNull().default(5),
  adminDefaultEntry: text("admin_default_entry").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});
